# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 528b3b998ae873450eed24c5fb38956392279fee45cc47b3c5430cdf02848461f5a7a7d8d5c3a57ae5455dcef81b1a318df26694f39d4d2b72f6f410a6438068

test:
  secret_key_base: 6e8da19c92c1ac044e6572cffb846e69c7a2f633744a16e5bcf9a6ff35fb88658780227170cff650896e47b43dc6415176a32829fcfdaed2c468806184373df0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
